server:
  port: 7002
spring:
  application:
    name: service-vod
  profiles:
    active: dev
  #配置上传文件大小
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  # nacos配置
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
#keyid和keysecret
aliyun:
  vod:
   file:
     keyid: ####
     keysecret: ###



