#端口
server:
  port: 7001
spring:
  application:
#服务名
   name: service-edu
#环境设置 dev、test、online
  rofiles:
   active: dev
#数据库配置
  datasource:
   driver-class-name: com.mysql.jdbc.Driver
   url: jdbc:mysql://localhost:3306/learning?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
   username: root
   password: 123456
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#mybatis日志
mybatis-plus:
  configuration:
   log-impl: org.apache.ibatis.logging.stdout.StdOutImpl